name: 'Azure key vault - Get Secrets'
description: 'Get Secrets from Azure Key Vault instance and set as output variables. github.com/azure/actions'
inputs:
  keyvault:
    description: 'Name of the azure key vault'
    required: true
  secrets:
    description: 'Name of the secret to be fetched' #Comma separated list of secret keys can be specified
    required: true
  environment:
    description: 'Name of the environment. Supported values are AzureStack, AzureCloud. Default being AzureCloud'
    required: false
    default: AzureCloud
branding:
  icon: 'akv.svg'
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/main.js'